[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/exchange-token"
  to = "/.netlify/functions/exchange-token"
  status = 200

[[redirects]]
  from = "/get-csrf-token"
  to = "/.netlify/functions/get-csrf-token"
  status = 200

[build]
  functions = "netlify/functions"

[build.environment]
  VITE_DEPLOY_PLATFORM = "NETLIFY"
